
import { SessionData, VocabItem } from '../types';

export const generateSessionPDF = async (session: SessionData) => {
  const { jsPDF } = (window as any).jspdf;
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();

  // --- Header Styling ---
  doc.setFillColor(37, 99, 235); // Blue-600
  doc.rect(0, 0, pageWidth, 45, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(28);
  doc.setFont(undefined, 'bold');
  doc.text('LinguistBuddy AI', 20, 25);
  
  doc.setFontSize(12);
  doc.setFont(undefined, 'normal');
  doc.text(`YOUR ${session.language.name.toUpperCase()} LEARNING REPORT`, 20, 35);
  
  doc.setFontSize(10);
  doc.text(new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' }), pageWidth - 20, 25, { align: 'right' });

  // --- Content Start ---
  let y = 60;

  // --- Session Highlights Section ---
  doc.setFillColor(248, 250, 252); // Slate-50
  doc.rect(15, y - 5, pageWidth - 30, 35, 'F');
  doc.setDrawColor(226, 232, 240); // Slate-200
  doc.rect(15, y - 5, pageWidth - 30, 35, 'S');
  
  // Left Accent Line
  doc.setDrawColor(37, 99, 235); // Blue-600
  doc.setLineWidth(1.5);
  doc.line(15, y - 5, 15, y + 30);
  doc.setLineWidth(0.2);

  doc.setTextColor(30, 41, 59); // Slate-800
  doc.setFontSize(14);
  doc.setFont(undefined, 'bold');
  doc.text('Session Summary', 25, y + 5);
  
  doc.setFontSize(10);
  doc.setFont(undefined, 'normal');
  doc.setTextColor(71, 85, 105); // Slate-600
  const splitSummary = doc.splitTextToSize(session.summary || "You had a great conversation practicing your fluency today!", pageWidth - 50);
  doc.text(splitSummary, 25, y + 15);

  y += 50;

  // --- Vocabulary Section ---
  doc.setTextColor(30, 41, 59);
  doc.setFontSize(16);
  doc.setFont(undefined, 'bold');
  doc.text('New Vocabulary & Concepts', 20, y);
  y += 10;

  session.vocabulary.forEach((item, index) => {
    // Check for page overflow
    if (y > pageHeight - 40) {
      doc.addPage();
      y = 20;
    }

    // Word Bubble/Card
    doc.setFillColor(255, 255, 255);
    doc.setDrawColor(241, 245, 249); // Slate-100
    doc.rect(20, y, pageWidth - 40, 32, 'F');
    doc.rect(20, y, pageWidth - 40, 32, 'S');

    // Numbering
    doc.setFillColor(239, 246, 255); // Blue-50
    doc.circle(28, y + 8, 4, 'F');
    doc.setTextColor(37, 99, 235);
    doc.setFontSize(9);
    doc.setFont(undefined, 'bold');
    doc.text(`${index + 1}`, 28, y + 9, { align: 'center' });

    // The Word
    doc.setTextColor(15, 23, 42); // Slate-900
    doc.setFontSize(14);
    doc.text(item.word, 35, y + 9);

    // Pronunciation Tag
    const pronWidth = doc.getTextWidth(`[${item.pronunciation}]`) + 6;
    doc.setFillColor(241, 245, 249);
    doc.roundedRect(pageWidth - 25 - pronWidth, y + 4, pronWidth, 7, 2, 2, 'F');
    doc.setTextColor(100, 116, 139);
    doc.setFontSize(8);
    doc.setFont(undefined, 'normal');
    doc.text(`[${item.pronunciation}]`, pageWidth - 25 - (pronWidth/2), y + 8.5, { align: 'center' });

    // Translation
    doc.setTextColor(37, 99, 235);
    doc.setFontSize(10);
    doc.setFont(undefined, 'bold');
    doc.text(item.translation, 35, y + 16);

    // Example Sentence
    doc.setTextColor(100, 116, 139);
    doc.setFont(undefined, 'italic');
    doc.setFontSize(9);
    const splitEx = doc.splitTextToSize(`Example: "${item.example}"`, pageWidth - 60);
    doc.text(splitEx, 35, y + 23);

    y += 38;
  });

  // Bottom watermark
  doc.setTextColor(203, 213, 225); // Slate-300
  doc.setFontSize(8);
  doc.text('Generated by LinguistBuddy AI - Your constant language partner', pageWidth / 2, pageHeight - 10, { align: 'center' });

  return doc.output('blob');
};
